### ISSUE TITLE
Adding Enderal to LOOT

### ISSUE THREAD

**Issue by AerosDragonewt99** [loot/enderal#25]
How to properly install Enderal and its master list to LOOT? If so, can anyone show me how it is done? Also, is this project not finished? I was comparing the files shown on this page versus the versions shown on the other games in the AppData\Local\LOOT\ file. It seems to be missing some of the files and folders versus the other games which leave me wondering how far this has gone regarding development.

**Comment by sibir-ine** [comment]
@AerosDragonewt99 You can read the discussion in https://github.com/loot/loot/issues/1383 to see how to use LOOT with Enderal properly, or you can download & install the [latest snapshot](https://loot.jfrog.io/ui/repos/tree/General/loot) of LOOT for native support. This masterlist is practically empty as Enderal support isn't included in the latest stable release of LOOT, but feel free to suggest metadata to add.

**Comment by n8ohu** [comment]
One thing to note; if you install the snapshot, you will probably have to delete your settings.toml to make sure LOOT picks up the new available settings for games. It didn't automatically update that when I installed it today.

**Comment by sibir-ine** [comment]
@AerosDragonewt99 Do you still have any more questions regarding LOOT's Enderal support? If not, I'll close this issue in a bit.

**Comment by sibir-ine** [comment]
@AerosDragonewt99 I'll close this then. Feel free to let us know if you have more questions.
